spring:
  application:
    name: BibliotechAPI
  datasource:
    url: jdbc:h2:file:./data/BibliotecaDb
    driver: org.h2.Driver
    username: lucas
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
